apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260616-234612-ix1yqrhzfa49-service
spec:
  selector:
    app: enterprise-system-20260616-234612-ix1yqrhzfa49
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
